// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="encode_encode,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.232054,HLS_SYN_LAT=157,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3788,HLS_SYN_LUT=4604,HLS_VERSION=2022_2}" *)

module encode (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xin1,
        xin2,
        ap_return,
        locking_key
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] xin1;
input  [31:0] xin2;
output  [31:0] ap_return;

input[149:0] locking_key;
wire [149:0] working_key;

reg ap_done;
reg ap_idle;
reg ap_ready;


(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] tqmf_address0;
reg    tqmf_ce0;
reg    tqmf_we0;
reg   [31:0] tqmf_d0;
wire   [31:0] tqmf_q0;
reg   [4:0] tqmf_address1;
reg    tqmf_ce1;
reg    tqmf_we1;
wire   [31:0] tqmf_q1;
reg   [2:0] delay_bpl_address0;
reg    delay_bpl_ce0;
reg    delay_bpl_we0;
reg   [31:0] delay_bpl_d0;
wire   [31:0] delay_bpl_q0;
reg   [2:0] delay_bpl_address1;
reg    delay_bpl_ce1;
wire   [31:0] delay_bpl_q1;
reg   [2:0] delay_dltx_address0;
reg    delay_dltx_ce0;
reg    delay_dltx_we0;
reg   [15:0] delay_dltx_d0;
wire   [15:0] delay_dltx_q0;
reg   [2:0] delay_dltx_address1;
reg    delay_dltx_ce1;
reg    delay_dltx_we1;
reg   [15:0] delay_dltx_d1;
wire   [15:0] delay_dltx_q1;
reg   [30:0] rlt1;
reg  signed [15:0] al1;
reg   [30:0] rlt2;
reg  signed [14:0] al2;
reg   [14:0] detl;
wire   [4:0] quant26bt_pos_address0;
reg    quant26bt_pos_ce0;
wire   [5:0] quant26bt_pos_q0;
wire   [4:0] quant26bt_neg_address0;
reg    quant26bt_neg_ce0;
wire   [5:0] quant26bt_neg_q0;
wire   [3:0] qq4_code4_table_address0;
reg    qq4_code4_table_ce0;
wire  signed [15:0] qq4_code4_table_q0;
reg   [14:0] nbl;
wire   [3:0] wl_code_table_address0;
reg    wl_code_table_ce0;
wire   [12:0] wl_code_table_q0;
reg   [4:0] ilb_table_address0;
reg    ilb_table_ce0;
wire   [11:0] ilb_table_q0;
reg  signed [31:0] plt1;
reg  signed [31:0] plt2;
reg   [2:0] delay_bph_address0;
reg    delay_bph_ce0;
reg    delay_bph_we0;
reg   [31:0] delay_bph_d0;
wire   [31:0] delay_bph_q0;
reg   [2:0] delay_bph_address1;
reg    delay_bph_ce1;
wire   [31:0] delay_bph_q1;
reg   [2:0] delay_dhx_address0;
reg    delay_dhx_ce0;
reg    delay_dhx_we0;
reg   [31:0] delay_dhx_d0;
wire   [31:0] delay_dhx_q0;
reg   [2:0] delay_dhx_address1;
reg    delay_dhx_ce1;
reg    delay_dhx_we1;
reg   [31:0] delay_dhx_d1;
wire   [31:0] delay_dhx_q1;
reg   [30:0] rh1;
reg  signed [15:0] ah1;
reg   [30:0] rh2;
reg  signed [14:0] ah2;
reg   [14:0] deth;
reg   [14:0] nbh;
reg  signed [31:0] ph1;
reg  signed [31:0] ph2;
reg  signed [31:0] reg_552;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
reg  signed [15:0] reg_556;
wire    ap_CS_fsm_state20;
reg  signed [31:0] reg_562;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
reg  signed [31:0] delay_bpl_load_reg_2169;
wire   [37:0] mul_ln188_fu_573_p2;
reg   [37:0] mul_ln188_reg_2174;
wire   [47:0] zl_fu_586_p2;
reg   [47:0] zl_reg_2179;
wire   [36:0] xa_fu_616_p2;
reg   [36:0] xa_reg_2184;
wire    ap_CS_fsm_state4;
wire   [38:0] mul_ln203_fu_627_p2;
reg   [38:0] mul_ln203_reg_2189;
wire    ap_CS_fsm_state8;
wire   [36:0] sub_ln204_fu_657_p2;
reg   [36:0] sub_ln204_reg_2194;
wire   [46:0] mul_ln529_fu_695_p2;
reg   [46:0] mul_ln529_reg_2208;
wire   [46:0] mul_ln533_fu_717_p2;
reg   [46:0] mul_ln533_reg_2213;
reg   [31:0] trunc_ln_reg_2218;
wire    ap_CS_fsm_state9;
reg   [31:0] trunc_ln1_reg_2223;
reg   [31:0] trunc_ln3_reg_2228;
reg   [30:0] trunc_ln228_1_reg_2233;
wire   [31:0] trunc_ln2_fu_806_p4;
reg   [31:0] trunc_ln2_reg_2238;
wire    ap_CS_fsm_state10;
wire   [30:0] add_ln229_fu_831_p2;
reg   [30:0] add_ln229_reg_2243;
wire   [0:0] tmp_2_fu_846_p3;
reg   [0:0] tmp_2_reg_2251;
wire   [31:0] m_4_fu_860_p3;
reg   [31:0] m_4_reg_2256;
wire   [0:0] grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_return;
reg   [0:0] targetBlock_reg_2261;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire   [5:0] ril_2_fu_885_p3;
reg   [5:0] ril_2_reg_2276;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [14:0] trunc_ln563_fu_981_p1;
reg   [14:0] trunc_ln563_reg_2301;
wire   [0:0] icmp_ln570_fu_985_p2;
reg   [0:0] icmp_ln570_reg_2306;
reg   [3:0] trunc_ln8_reg_2311;
wire    ap_CS_fsm_state15;
wire  signed [23:0] sext_ln531_fu_1057_p1;
reg  signed [23:0] sext_ln531_reg_2321;
wire    ap_CS_fsm_state17;
wire  signed [21:0] sext_ln533_fu_1060_p1;
reg  signed [21:0] sext_ln533_reg_2326;
wire  signed [15:0] trunc_ln5_fu_1063_p4;
reg   [15:0] trunc_ln5_reg_2331;
wire  signed [30:0] sext_ln239_fu_1077_p1;
reg  signed [30:0] sext_ln239_reg_2337;
wire  signed [31:0] add_ln246_fu_1081_p2;
reg  signed [31:0] add_ln246_reg_2342;
wire   [0:0] icmp_ln593_fu_1086_p2;
reg   [0:0] icmp_ln593_reg_2348;
reg   [0:0] tmp_8_reg_2352;
wire    ap_CS_fsm_state18;
reg   [10:0] tmp_3_reg_2358;
reg   [0:0] tmp_9_reg_2363;
reg   [14:0] trunc_ln7_reg_2368;
wire   [15:0] apl2_fu_1245_p2;
reg   [15:0] apl2_reg_2373;
wire   [0:0] icmp_ln642_fu_1251_p2;
reg   [0:0] icmp_ln642_reg_2378;
wire   [16:0] apl1_fu_1290_p2;
reg   [16:0] apl1_reg_2383;
reg  signed [31:0] delay_bph_load_reg_2389;
wire   [14:0] wd3_1_fu_1326_p2;
reg   [14:0] wd3_1_reg_2394;
wire   [63:0] zl_5_fu_1339_p2;
reg   [63:0] zl_5_reg_2400;
wire    ap_CS_fsm_state21;
wire   [46:0] mul_ln529_1_fu_1437_p2;
reg   [46:0] mul_ln529_1_reg_2422;
wire    ap_CS_fsm_state22;
wire   [46:0] mul_ln533_1_fu_1459_p2;
reg   [46:0] mul_ln533_1_reg_2427;
wire   [31:0] trunc_ln521_1_fu_1468_p4;
reg   [31:0] trunc_ln521_1_reg_2432;
wire    ap_CS_fsm_state23;
wire   [30:0] add_ln280_fu_1518_p2;
reg   [30:0] add_ln280_reg_2437;
wire   [31:0] sub_ln280_fu_1524_p2;
reg   [31:0] sub_ln280_reg_2442;
reg   [0:0] tmp_11_reg_2449;
wire   [0:0] icmp_ln293_fu_1569_p2;
reg   [0:0] icmp_ln293_reg_2455;
wire    ap_CS_fsm_state24;
wire   [1:0] select_ln297_fu_1589_p3;
reg   [1:0] select_ln297_reg_2460;
wire    ap_CS_fsm_state25;
wire   [31:0] tmp_fu_1596_p6;
reg  signed [31:0] tmp_reg_2465;
wire   [14:0] trunc_ln677_fu_1700_p1;
reg   [14:0] trunc_ln677_reg_2470;
wire   [0:0] icmp_ln684_fu_1704_p2;
reg   [0:0] icmp_ln684_reg_2475;
reg   [31:0] dlt_assign_3_reg_2480;
wire    ap_CS_fsm_state26;
reg   [30:0] trunc_ln11_reg_2488;
reg   [3:0] trunc_ln579_1_reg_2493;
wire  signed [23:0] sext_ln531_1_fu_1779_p1;
reg  signed [23:0] sext_ln531_1_reg_2503;
wire    ap_CS_fsm_state27;
wire  signed [21:0] sext_ln533_2_fu_1782_p1;
reg  signed [21:0] sext_ln533_2_reg_2508;
wire  signed [31:0] add_ln306_fu_1814_p2;
reg  signed [31:0] add_ln306_reg_2513;
wire   [0:0] icmp_ln593_1_fu_1818_p2;
reg   [0:0] icmp_ln593_1_reg_2519;
reg   [0:0] tmp_13_reg_2523;
wire    ap_CS_fsm_state28;
reg   [10:0] tmp_6_reg_2529;
reg   [0:0] tmp_14_reg_2534;
reg   [14:0] trunc_ln639_1_reg_2539;
wire   [15:0] apl2_3_fu_1976_p2;
reg   [15:0] apl2_3_reg_2544;
wire    ap_CS_fsm_state29;
wire   [0:0] icmp_ln642_1_fu_1982_p2;
reg   [0:0] icmp_ln642_1_reg_2549;
wire   [16:0] apl1_4_fu_2021_p2;
reg   [16:0] apl1_4_reg_2554;
reg   [31:0] delay_dhx_load_2_reg_2560;
wire   [14:0] wd3_3_fu_2057_p2;
reg   [14:0] wd3_3_reg_2565;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_ready;
wire   [46:0] grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out_ap_vld;
wire   [46:0] grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out_ap_vld;
wire   [4:0] grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce0;
wire   [4:0] grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce1;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_ready;
wire   [45:0] grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out_ap_vld;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_ce0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_ready;
wire   [4:0] grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_we0;
wire   [31:0] grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_d0;
wire   [4:0] grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce1;
wire    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_ready;
wire   [4:0] grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out;
wire    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out_ap_vld;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_ready;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_ce0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_we0;
wire   [31:0] grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_d0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce1;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_ready;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_we0;
wire   [31:0] grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_d0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce1;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_ready;
wire   [45:0] grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out_ap_vld;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_ce0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_ready;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_ce0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_we0;
wire   [31:0] grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_d0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce1;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_done;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_idle;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_ready;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address0;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce0;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_we0;
wire   [31:0] grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_d0;
wire   [2:0] grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address1;
wire    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce1;
reg    grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [46:0] xb_2_loc_fu_322;
reg   [46:0] xa_2_loc_fu_318;
reg    grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg;
reg   [45:0] zl_1_loc_fu_314;
reg    grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg;
reg    grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg;
reg   [4:0] mil_loc_fu_310;
reg    grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg;
reg    grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg;
reg    grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg;
reg   [45:0] zl_4_loc_fu_306;
reg    grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg;
reg    grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg;
wire   [63:0] zext_ln556_fu_879_p1;
wire   [63:0] zext_ln236_fu_902_p1;
wire   [63:0] zext_ln582_fu_1023_p1;
wire   [63:0] zext_ln582_1_fu_1774_p1;
wire   [30:0] add_ln263_fu_1184_p2;
reg    ap_block_state18_on_subcall_done;
wire   [15:0] apl1_3_fu_1383_p3;
wire   [14:0] apl2_2_fu_1312_p3;
wire   [14:0] shl_ln3_fu_1043_p3;
wire    ap_CS_fsm_state16;
wire   [14:0] select_ln570_fu_991_p3;
wire   [30:0] add_ln321_fu_1915_p2;
reg    ap_block_state28_on_subcall_done;
wire   [15:0] apl1_7_fu_2101_p3;
wire   [14:0] apl2_5_fu_2043_p3;
wire   [14:0] shl_ln583_1_fu_1800_p3;
wire   [14:0] select_ln684_fu_1742_p3;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state32;
wire  signed [6:0] mul_ln188_fu_573_p1;
wire   [31:0] shl_ln_fu_592_p1;
wire   [35:0] shl_ln_fu_592_p3;
wire   [31:0] shl_ln194_1_fu_604_p1;
wire   [33:0] shl_ln194_1_fu_604_p3;
wire  signed [36:0] sext_ln194_fu_600_p1;
wire  signed [36:0] sext_ln194_1_fu_612_p1;
wire  signed [6:0] mul_ln203_fu_627_p1;
wire   [35:0] shl_ln1_fu_633_p3;
wire   [33:0] shl_ln204_1_fu_645_p3;
wire  signed [36:0] sext_ln204_2_fu_641_p1;
wire  signed [36:0] sext_ln204_3_fu_653_p1;
wire  signed [31:0] pl_fu_679_p3;
wire  signed [31:0] pl2_fu_701_p3;
wire  signed [46:0] sext_ln204_1_fu_729_p1;
wire  signed [46:0] sext_ln203_fu_732_p1;
wire   [46:0] xb_fu_741_p2;
wire   [46:0] xa_4_fu_735_p2;
wire   [46:0] add_ln214_fu_747_p2;
wire   [46:0] sub_ln215_fu_763_p2;
wire   [46:0] pl_1_fu_779_p2;
wire   [30:0] trunc_ln4_fu_816_p4;
wire   [31:0] add_ln228_fu_826_p2;
wire   [31:0] sub_ln229_fu_836_p2;
wire   [31:0] m_fu_854_p2;
wire   [4:0] select_ln546_fu_872_p3;
wire   [3:0] lshr_ln_fu_892_p4;
wire   [21:0] shl_ln2_fu_923_p3;
wire   [22:0] zext_ln566_1_fu_931_p1;
wire   [22:0] zext_ln566_fu_919_p1;
wire   [22:0] sub_ln566_fu_935_p2;
wire   [15:0] trunc_ln6_fu_941_p4;
wire  signed [16:0] sext_ln567_1_fu_955_p1;
wire  signed [16:0] sext_ln567_fu_951_p1;
wire   [16:0] add_ln567_fu_959_p2;
wire   [0:0] tmp_5_fu_965_p3;
wire   [16:0] select_ln568_fu_973_p3;
wire   [4:0] wd1_fu_1003_p4;
wire   [3:0] sub_ln582_fu_1028_p2;
wire   [11:0] sub_ln582cast_fu_1033_p1;
wire   [11:0] wd3_fu_1037_p2;
wire  signed [15:0] sext_ln531_fu_1057_p0;
wire  signed [14:0] sext_ln533_fu_1060_p0;
wire  signed [30:0] grp_fu_2125_p2;
wire  signed [31:0] sext_ln236_1_fu_1073_p1;
wire  signed [15:0] wd2_fu_1100_p1;
wire  signed [31:0] mul_ln628_fu_1114_p1;
wire  signed [63:0] sext_ln628_fu_1107_p1;
wire   [63:0] mul_ln628_fu_1114_p2;
wire   [17:0] wd2_fu_1100_p3;
wire   [17:0] sub_ln629_fu_1128_p2;
wire  signed [31:0] mul_ln631_fu_1148_p1;
wire   [63:0] mul_ln631_fu_1148_p2;
wire  signed [14:0] shl_ln6_fu_1162_p1;
wire   [21:0] shl_ln6_fu_1162_p3;
wire   [21:0] sub_ln639_fu_1169_p2;
wire  signed [15:0] tmp_4_fu_1210_p1;
wire   [10:0] tmp_4_fu_1210_p4;
wire   [10:0] select_ln628_fu_1219_p3;
wire  signed [15:0] sext_ln639_fu_1229_p1;
wire   [15:0] select_ln639_fu_1232_p3;
wire   [15:0] add_ln639_fu_1239_p2;
wire  signed [15:0] sext_ln631_2_fu_1225_p1;
wire  signed [15:0] shl_ln7_fu_1257_p1;
wire   [23:0] shl_ln7_fu_1257_p3;
wire   [23:0] sub_ln656_fu_1264_p2;
wire   [15:0] trunc_ln9_fu_1269_p4;
wire   [16:0] select_ln657_fu_1283_p3;
wire  signed [16:0] sext_ln657_fu_1279_p1;
wire   [15:0] apl2_1_fu_1296_p3;
wire   [0:0] icmp_ln644_fu_1306_p2;
wire   [14:0] trunc_ln626_fu_1302_p1;
wire   [16:0] zext_ln655_fu_1345_p1;
wire   [0:0] icmp_ln667_fu_1351_p2;
wire   [16:0] apl1_1_fu_1356_p3;
wire   [15:0] zext_ln655_1_fu_1348_p1;
wire  signed [15:0] apl1_2_fu_1367_p2;
wire  signed [16:0] sext_ln669_fu_1373_p1;
wire   [0:0] icmp_ln669_fu_1377_p2;
wire   [15:0] trunc_ln655_fu_1363_p1;
wire  signed [31:0] pl_2_fu_1421_p3;
wire  signed [31:0] pl2_1_fu_1443_p3;
wire   [46:0] pl_3_fu_1478_p2;
wire   [31:0] trunc_ln534_1_fu_1482_p4;
wire   [30:0] trunc_ln278_1_fu_1502_p4;
wire   [30:0] trunc_ln10_fu_1492_p4;
wire   [31:0] add_ln278_fu_1512_p2;
wire   [24:0] decis_1_fu_1544_p1;
wire  signed [24:0] grp_fu_2132_p2;
wire   [12:0] decis_1_fu_1544_p4;
wire   [0:0] tmp_10_fu_1537_p3;
wire   [31:0] m_2_fu_1557_p2;
wire   [31:0] m_3_fu_1562_p3;
wire   [31:0] zext_ln292_2_fu_1553_p1;
wire   [1:0] select_ln294_fu_1582_p3;
wire   [1:0] select_ln284_fu_1575_p3;
wire   [21:0] shl_ln8_fu_1618_p3;
wire   [22:0] zext_ln680_1_fu_1626_p1;
wire   [22:0] zext_ln680_fu_1614_p1;
wire   [22:0] sub_ln680_fu_1630_p2;
wire  signed [15:0] wd_1_fu_1636_p4;
wire   [31:0] tmp_1_fu_1650_p6;
wire  signed [31:0] sext_ln680_fu_1646_p1;
wire  signed [30:0] sext_ln681_fu_1668_p1;
wire   [30:0] trunc_ln681_fu_1664_p1;
wire   [31:0] add_ln681_fu_1672_p2;
wire   [0:0] tmp_12_fu_1684_p3;
wire   [30:0] add_ln677_fu_1678_p2;
wire   [30:0] select_ln682_fu_1692_p3;
wire   [14:0] mul_ln297_fu_1716_p1;
wire   [46:0] mul_ln297_fu_1716_p2;
wire   [4:0] wd1_1_fu_1754_p4;
wire  signed [15:0] sext_ln531_1_fu_1779_p0;
wire  signed [14:0] sext_ln533_2_fu_1782_p0;
wire   [3:0] sub_ln582_1_fu_1785_p2;
wire   [11:0] sub_ln582_1cast_fu_1790_p1;
wire   [11:0] wd3_2_fu_1794_p2;
wire  signed [15:0] wd2_1_fu_1831_p1;
wire  signed [31:0] mul_ln628_1_fu_1845_p1;
wire  signed [63:0] sext_ln628_2_fu_1838_p1;
wire   [63:0] mul_ln628_1_fu_1845_p2;
wire   [17:0] wd2_1_fu_1831_p3;
wire   [17:0] sub_ln629_1_fu_1859_p2;
wire  signed [31:0] mul_ln631_1_fu_1879_p1;
wire   [63:0] mul_ln631_1_fu_1879_p2;
wire  signed [14:0] shl_ln639_1_fu_1893_p1;
wire   [21:0] shl_ln639_1_fu_1893_p3;
wire   [21:0] sub_ln639_1_fu_1900_p2;
wire  signed [15:0] tmp_7_fu_1941_p1;
wire   [10:0] tmp_7_fu_1941_p4;
wire   [10:0] select_ln628_1_fu_1950_p3;
wire  signed [15:0] sext_ln639_1_fu_1960_p1;
wire   [15:0] select_ln639_1_fu_1963_p3;
wire   [15:0] add_ln639_2_fu_1970_p2;
wire  signed [15:0] sext_ln631_3_fu_1956_p1;
wire  signed [15:0] shl_ln656_1_fu_1988_p1;
wire   [23:0] shl_ln656_1_fu_1988_p3;
wire   [23:0] sub_ln656_1_fu_1995_p2;
wire   [15:0] trunc_ln656_1_fu_2000_p4;
wire   [16:0] select_ln657_1_fu_2014_p3;
wire  signed [16:0] sext_ln657_1_fu_2010_p1;
wire   [15:0] apl2_4_fu_2027_p3;
wire   [0:0] icmp_ln644_1_fu_2037_p2;
wire   [14:0] trunc_ln626_1_fu_2033_p1;
wire   [16:0] zext_ln655_2_fu_2063_p1;
wire   [0:0] icmp_ln667_1_fu_2069_p2;
wire   [16:0] apl1_5_fu_2074_p3;
wire   [15:0] zext_ln655_3_fu_2066_p1;
wire  signed [15:0] apl1_6_fu_2085_p2;
wire  signed [16:0] sext_ln669_1_fu_2091_p1;
wire   [0:0] icmp_ln669_1_fu_2095_p2;
wire   [15:0] trunc_ln655_1_fu_2081_p1;
wire   [7:0] or_ln_fu_2115_p3;
wire   [14:0] grp_fu_2125_p1;
wire   [14:0] grp_fu_2132_p0;
wire   [9:0] grp_fu_2132_p1;
reg    grp_fu_2132_ce;
reg   [31:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_block_state5_on_subcall_done;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_block_state11_on_subcall_done;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire   [30:0] grp_fu_2125_p10;
wire   [24:0] grp_fu_2132_p00;
wire   [46:0] mul_ln297_fu_1716_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 rlt1 = 31'd0;
#0 al1 = 16'd0;
#0 rlt2 = 31'd0;
#0 al2 = 15'd0;
#0 detl = 15'd0;
#0 nbl = 15'd0;
#0 plt1 = 32'd0;
#0 plt2 = 32'd0;
#0 rh1 = 31'd0;
#0 ah1 = 16'd0;
#0 rh2 = 31'd0;
#0 ah2 = 15'd0;
#0 deth = 15'd0;
#0 nbh = 15'd0;
#0 ph1 = 32'd0;
#0 ph2 = 32'd0;
#0 grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg = 1'b0;
#0 grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg = 1'b0;
end

encode_tqmf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
tqmf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tqmf_address0),
    .ce0(tqmf_ce0),
    .we0(tqmf_we0),
    .d0(tqmf_d0),
    .q0(tqmf_q0),
    .address1(tqmf_address1),
    .ce1(tqmf_ce1),
    .we1(tqmf_we1),
    .d1(xin1),
    .q1(tqmf_q1)
);

encode_delay_bpl_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
delay_bpl_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_bpl_address0),
    .ce0(delay_bpl_ce0),
    .we0(delay_bpl_we0),
    .d0(delay_bpl_d0),
    .q0(delay_bpl_q0),
    .address1(delay_bpl_address1),
    .ce1(delay_bpl_ce1),
    .q1(delay_bpl_q1)   
);

encode_delay_dltx_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
delay_dltx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_dltx_address0),
    .ce0(delay_dltx_ce0),
    .we0(delay_dltx_we0),
    .d0(delay_dltx_d0),
    .q0(delay_dltx_q0),
    .address1(delay_dltx_address1),
    .ce1(delay_dltx_ce1),
    .we1(delay_dltx_we1),
    .d1(delay_dltx_d1),
    .q1(delay_dltx_q1)   
);

encode_quant26bt_pos_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 31 ),
    .AddressWidth( 5 ))
quant26bt_pos_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(quant26bt_pos_address0),
    .ce0(quant26bt_pos_ce0),
    .q0(quant26bt_pos_q0)   
);

encode_quant26bt_neg_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 31 ),
    .AddressWidth( 5 ))
quant26bt_neg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(quant26bt_neg_address0),
    .ce0(quant26bt_neg_ce0),
    .q0(quant26bt_neg_q0)    
);

encode_qq4_code4_table_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
qq4_code4_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(qq4_code4_table_address0),
    .ce0(qq4_code4_table_ce0),
    .q0(qq4_code4_table_q0)   
);

encode_wl_code_table_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
wl_code_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(wl_code_table_address0),
    .ce0(wl_code_table_ce0),
    .q0(wl_code_table_q0)   
);

encode_ilb_table_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
ilb_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ilb_table_address0),
    .ce0(ilb_table_ce0),
    .q0(ilb_table_q0)  
);

encode_delay_bpl_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
delay_bph_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_bph_address0),
    .ce0(delay_bph_ce0),
    .we0(delay_bph_we0),
    .d0(delay_bph_d0),
    .q0(delay_bph_q0),
    .address1(delay_bph_address1),
    .ce1(delay_bph_ce1),
    .q1(delay_bph_q1)
);

encode_delay_dhx_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
delay_dhx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delay_dhx_address0),
    .ce0(delay_dhx_ce0),
    .we0(delay_dhx_we0),
    .d0(delay_dhx_d0),
    .q0(delay_dhx_q0),
    .address1(delay_dhx_address1),
    .ce1(delay_dhx_ce1),
    .we1(delay_dhx_we1),
    .d1(delay_dhx_d1),
    .q1(delay_dhx_q1)
);

encode_encode_Pipeline_VITIS_LOOP_197_1 grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_ready),
    .sext_ln188_1(mul_ln188_reg_2174),
    .sext_ln188(xa_reg_2184),
    .xb_2_out(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out),
    .xb_2_out_ap_vld(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out_ap_vld),
    .xa_2_out(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out),
    .xa_2_out_ap_vld(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out_ap_vld),
    .tqmf_address0(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address0),
    .tqmf_ce0(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce0),
    .tqmf_q0(tqmf_q0),
    .tqmf_address1(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address1),
    .tqmf_ce1(grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce1),
    .tqmf_q1(tqmf_q1),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_518_1 grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_ready),
    .zl(zl_reg_2179),
    .zl_1_out(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out),
    .zl_1_out_ap_vld(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out_ap_vld),
    .delay_bpl_address0(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_address0),
    .delay_bpl_ce0(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_ce0),
    .delay_bpl_q0(delay_bpl_q0),
    .delay_dltx_address0(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_address0),
    .delay_dltx_ce0(grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_ce0),
    .delay_dltx_q0(delay_dltx_q0),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_208_2 grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_ready),
    .tqmf_address0(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address0),
    .tqmf_ce0(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce0),
    .tqmf_we0(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_we0),
    .tqmf_d0(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_d0),
    .tqmf_address1(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address1),
    .tqmf_ce1(grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce1),
    .tqmf_q1(tqmf_q1),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_546_1 grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_ready),
    .zext_ln546(detl),
    .m_4(m_4_reg_2256),
    .mil_out(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out),
    .mil_out_ap_vld(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out_ap_vld),
    .ap_return(grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_return),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_602_2 grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_ready),
    .conv8_i45(trunc_ln5_reg_2331),
    .delay_dltx_address0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_address0),
    .delay_dltx_ce0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_ce0),
    .delay_dltx_q0(delay_dltx_q0),
    .delay_bpl_address0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address0),
    .delay_bpl_ce0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce0),
    .delay_bpl_we0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_we0),
    .delay_bpl_d0(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_d0),
    .delay_bpl_address1(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address1),
    .delay_bpl_ce1(grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce1),
    .delay_bpl_q1(delay_bpl_q1),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_595_1 grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_ready),
    .delay_bpl_address0(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address0),
    .delay_bpl_ce0(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce0),
    .delay_bpl_we0(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_we0),
    .delay_bpl_d0(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_d0),
    .delay_bpl_address1(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address1),
    .delay_bpl_ce1(grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce1),
    .delay_bpl_q1(delay_bpl_q1),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_518_11 grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_ready),
    .zl_3(zl_5_reg_2400),
    .zl_4_out(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out),
    .zl_4_out_ap_vld(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out_ap_vld),
    .delay_bph_address0(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_address0),
    .delay_bph_ce0(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_ce0),
    .delay_bph_q0(delay_bph_q0),
    .delay_dhx_address0(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_address0),
    .delay_dhx_ce0(grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_ce0),
    .delay_dhx_q0(delay_dhx_q0),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_602_23 grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_ready),
    .conv8_i134(dlt_assign_3_reg_2480),
    .delay_dhx_address0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_address0),
    .delay_dhx_ce0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_ce0),
    .delay_dhx_q0(delay_dhx_q0),
    .delay_bph_address0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address0),
    .delay_bph_ce0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce0),
    .delay_bph_we0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_we0),
    .delay_bph_d0(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_d0),
    .delay_bph_address1(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address1),
    .delay_bph_ce1(grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce1),
    .delay_bph_q1(delay_bph_q1),    
    .locking_key(locking_key[149:0])
);

encode_encode_Pipeline_VITIS_LOOP_595_12 grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start),
    .ap_done(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_done),
    .ap_idle(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_idle),
    .ap_ready(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_ready),
    .delay_bph_address0(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address0),
    .delay_bph_ce0(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce0),
    .delay_bph_we0(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_we0),
    .delay_bph_d0(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_d0),
    .delay_bph_address1(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address1),
    .delay_bph_ce1(grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce1),
    .delay_bph_q1(delay_bph_q1),    
    .locking_key(locking_key[149:0])
);

encode_mul_32s_7s_38_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 38 ))
mul_32s_7s_38_1_1_U40(
    .din0(reg_552),
    .din1(mul_ln188_fu_573_p1),
    .dout(mul_ln188_fu_573_p2)    
);

encode_mul_16s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_16s_32s_48_1_1_U41(
    .din0(reg_556),
    .din1(delay_bpl_load_reg_2169),
    .dout(zl_fu_586_p2)   
);

encode_mul_32s_7s_39_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 39 ))
mul_32s_7s_39_1_1_U42(
    .din0(reg_552),
    .din1(mul_ln203_fu_627_p1),
    .dout(mul_ln203_fu_627_p2)    
);

encode_mul_16s_32s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 47 ))
mul_16s_32s_47_1_1_U43(
    .din0(al1),
    .din1(pl_fu_679_p3),
    .dout(mul_ln529_fu_695_p2)    
);

encode_mul_15s_32s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 47 ))
mul_15s_32s_47_1_1_U44(
    .din0(al2),
    .din1(pl2_fu_701_p3),
    .dout(mul_ln533_fu_717_p2)    
);

encode_mul_32s_32s_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_1_1_U45(
    .din0(plt1),
    .din1(mul_ln628_fu_1114_p1),
    .dout(mul_ln628_fu_1114_p2)    
);

encode_mul_32s_32s_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_1_1_U46(
    .din0(plt2),
    .din1(mul_ln631_fu_1148_p1),
    .dout(mul_ln631_fu_1148_p2)    
);

encode_mul_32s_32s_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_1_1_U47(
    .din0(reg_562),
    .din1(delay_bph_load_reg_2389),
    .dout(zl_5_fu_1339_p2)  
);

encode_mul_16s_32s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 47 ))
mul_16s_32s_47_1_1_U48(
    .din0(ah1),
    .din1(pl_2_fu_1421_p3),
    .dout(mul_ln529_1_fu_1437_p2)   
);

encode_mul_15s_32s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 47 ))
mul_15s_32s_47_1_1_U49(
    .din0(ah2),
    .din1(pl2_1_fu_1443_p3),
    .dout(mul_ln533_1_fu_1459_p2)  
);

encode_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U50(
    .din0(32'd4294959888),
    .din1(32'd4294965680),
    .din2(32'd7408),
    .din3(32'd1616),
    .din4(select_ln297_fu_1589_p3),
    .dout(tmp_fu_1596_p6) 
);

encode_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U51(
    .din0(32'd798),
    .din1(32'd4294967082),
    .din2(32'd798),
    .din3(32'd4294967082),
    .din4(select_ln297_fu_1589_p3),
    .dout(tmp_1_fu_1650_p6)
);

encode_mul_32s_15ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15ns_47_1_1_U52(
    .din0(tmp_reg_2465),
    .din1(mul_ln297_fu_1716_p1),
    .dout(mul_ln297_fu_1716_p2)   
);

encode_mul_32s_32s_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_1_1_U53(
    .din0(ph1),
    .din1(mul_ln628_1_fu_1845_p1),
    .dout(mul_ln628_1_fu_1845_p2)   
    
);

encode_mul_32s_32s_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_1_1_U54(
    .din0(ph2),
    .din1(mul_ln631_1_fu_1879_p1),
    .dout(mul_ln631_1_fu_1879_p2)
);

encode_mul_mul_16s_15ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mul_mul_16s_15ns_31_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(qq4_code4_table_q0),
    .din1(grp_fu_2125_p1),
    .ce(1'b1),
    .dout(grp_fu_2125_p2)
);

encode_mul_mul_15ns_10ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_mul_15ns_10ns_25_4_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2132_p0),
    .din1(grp_fu_2132_p1),
    .ce(grp_fu_2132_ce),
    .dout(grp_fu_2132_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[0] ^ working_key[1] ^ working_key[2]) begin
        grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1)^ working_key[3] ^ working_key[4]) begin
        grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[5] ^ working_key[6]) begin
        grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[7] ^ working_key[8]) begin
        grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[9] ^ working_key[10]) begin
        grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^working_key[11] ^ working_key[12]) begin
        grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln593_1_fu_1818_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
            grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[13] ^ working_key[14]) begin
        grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln593_fu_1086_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1) ^ working_key[15] ^ working_key[16]) begin
        grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln593_1_fu_1818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state27))) begin
            grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_rst == 1'b1)^ working_key[17] ^ working_key[18]) begin
        grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln593_fu_1086_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg <= 1'b1;
        end else if ((grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_ready == 1'b1)) begin
            grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30) ^ working_key[19]) begin
        reg_562 <= delay_dhx_q1;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_562 <= delay_dhx_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln229_reg_2243 <= add_ln229_fu_831_p2;
        m_4_reg_2256 <= m_4_fu_860_p3;
        tmp_2_reg_2251 <= sub_ln229_fu_836_p2[32'd31];
        trunc_ln2_reg_2238 <= {{zl_1_loc_fu_314[45:14]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln246_reg_2342 <= add_ln246_fu_1081_p2;
        icmp_ln593_reg_2348 <= icmp_ln593_fu_1086_p2;
        sext_ln239_reg_2337 <= sext_ln239_fu_1077_p1;
        sext_ln531_reg_2321 <= sext_ln531_fu_1057_p1;
        sext_ln533_reg_2326 <= sext_ln533_fu_1060_p1;
        trunc_ln5_reg_2331 <= {{grp_fu_2125_p2[30:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln280_reg_2437 <= add_ln280_fu_1518_p2;
        sub_ln280_reg_2442 <= sub_ln280_fu_1524_p2;
        tmp_11_reg_2449 <= sub_ln280_fu_1524_p2[32'd31];
        trunc_ln521_1_reg_2432 <= {{zl_4_loc_fu_306[45:14]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        add_ln306_reg_2513 <= add_ln306_fu_1814_p2;
        deth[14 : 3] <= shl_ln583_1_fu_1800_p3[14 : 3];
        icmp_ln593_1_reg_2519 <= icmp_ln593_1_fu_1818_p2;
        sext_ln531_1_reg_2503 <= sext_ln531_1_fu_1779_p1;
        sext_ln533_2_reg_2508 <= sext_ln533_2_fu_1782_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ah1 <= apl1_7_fu_2101_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ah2 <= apl2_5_fu_2043_p3;
        delay_dhx_load_2_reg_2560 <= delay_dhx_q0;
        wd3_3_reg_2565 <= wd3_3_fu_2057_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        al1 <= apl1_3_fu_1383_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        al2 <= apl2_2_fu_1312_p3;
        wd3_1_reg_2394 <= wd3_1_fu_1326_p2;
        zl_5_reg_2400 <= zl_5_fu_1339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        apl1_4_reg_2554 <= apl1_4_fu_2021_p2;
        apl2_3_reg_2544 <= apl2_3_fu_1976_p2;
        icmp_ln642_1_reg_2549 <= icmp_ln642_1_fu_1982_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        apl1_reg_2383 <= apl1_fu_1290_p2;
        apl2_reg_2373 <= apl2_fu_1245_p2;
        delay_bph_load_reg_2389 <= delay_bph_q0;
        icmp_ln642_reg_2378 <= icmp_ln642_fu_1251_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_bpl_load_reg_2169 <= delay_bpl_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        detl[14 : 3] <= shl_ln3_fu_1043_p3[14 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        dlt_assign_3_reg_2480 <= {{mul_ln297_fu_1716_p2[46:15]}};
        nbh <= select_ln684_fu_1742_p3;
        trunc_ln11_reg_2488 <= {{mul_ln297_fu_1716_p2[45:15]}};
        trunc_ln579_1_reg_2493 <= {{select_ln684_fu_1742_p3[14:11]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        icmp_ln293_reg_2455 <= icmp_ln293_fu_1569_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        icmp_ln570_reg_2306 <= icmp_ln570_fu_985_p2;
        trunc_ln563_reg_2301 <= trunc_ln563_fu_981_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        icmp_ln684_reg_2475 <= icmp_ln684_fu_1704_p2;
        select_ln297_reg_2460 <= select_ln297_fu_1589_p3;
        tmp_reg_2465 <= tmp_fu_1596_p6;
        trunc_ln677_reg_2470 <= trunc_ln677_fu_1700_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        mil_loc_fu_310 <= grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_mil_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln188_reg_2174 <= mul_ln188_fu_573_p2;
        zl_reg_2179 <= zl_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_ln203_reg_2189 <= mul_ln203_fu_627_p2;
        mul_ln529_reg_2208 <= mul_ln529_fu_695_p2;
        mul_ln533_reg_2213 <= mul_ln533_fu_717_p2;
        sub_ln204_reg_2194[36 : 2] <= sub_ln204_fu_657_p2[36 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        mul_ln529_1_reg_2422 <= mul_ln529_1_fu_1437_p2;
        mul_ln533_1_reg_2427 <= mul_ln533_1_fu_1459_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        nbl <= select_ln570_fu_991_p3;
        trunc_ln8_reg_2311 <= {{select_ln570_fu_991_p3[14:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
        ph1 <= add_ln306_reg_2513;
        ph2 <= ph1;
        rh1 <= add_ln321_fu_1915_p2;
        rh2 <= rh1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        plt1 <= add_ln246_reg_2342;
        plt2 <= plt1;
        rlt1 <= add_ln263_fu_1184_p2;
        rlt2 <= rlt1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_552 <= tqmf_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_556 <= delay_dltx_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ril_2_reg_2276 <= ril_2_fu_885_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        targetBlock_reg_2261 <= grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        tmp_13_reg_2523 <= mul_ln628_1_fu_1845_p2[32'd63];
        tmp_14_reg_2534 <= mul_ln631_1_fu_1879_p2[32'd63];
        tmp_6_reg_2529 <= {{sub_ln629_1_fu_1859_p2[17:7]}};
        trunc_ln639_1_reg_2539 <= {{sub_ln639_1_fu_1900_p2[21:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        tmp_3_reg_2358 <= {{sub_ln629_fu_1128_p2[17:7]}};
        tmp_8_reg_2352 <= mul_ln628_fu_1114_p2[32'd63];
        tmp_9_reg_2363 <= mul_ln631_fu_1148_p2[32'd63];
        trunc_ln7_reg_2368 <= {{sub_ln639_fu_1169_p2[21:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        trunc_ln1_reg_2223 <= {{sub_ln215_fu_763_p2[46:15]}};
        trunc_ln228_1_reg_2233 <= {{pl_1_fu_779_p2[45:15]}};
        trunc_ln3_reg_2228 <= {{pl_1_fu_779_p2[46:15]}};
        trunc_ln_reg_2218 <= {{add_ln214_fu_747_p2[46:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        xa_2_loc_fu_318 <= grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xa_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        xa_reg_2184[36 : 2] <= xa_fu_616_p2[36 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        xb_2_loc_fu_322 <= grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_xb_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        zl_1_loc_fu_314 <= grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_zl_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        zl_4_loc_fu_306 <= grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_zl_4_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0 ;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state18_on_subcall_done)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state28_on_subcall_done)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        delay_bph_address0 = 3'd0;
    end else if (((icmp_ln593_1_reg_2519 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_bph_address0 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address0;
    end else if (((icmp_ln593_1_reg_2519 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_bph_address0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_bph_address0 = grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_address0;
    end else begin
        delay_bph_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln593_1_reg_2519 == 1'd1)) begin
            delay_bph_address1 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_address1;
        end else if ((icmp_ln593_1_reg_2519 == 1'd0)) begin
            delay_bph_address1 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_address1;
        end else begin
            delay_bph_address1 = 'bx;
        end
    end else begin
        delay_bph_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_bph_ce0 = 1'b1;
    end else if (((icmp_ln593_1_reg_2519 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_bph_ce0 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce0;
    end else if (((icmp_ln593_1_reg_2519 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_bph_ce0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_bph_ce0 = grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_bph_ce0;
    end else begin
        delay_bph_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln593_1_reg_2519 == 1'd1)) begin
            delay_bph_ce1 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_ce1;
        end else if ((icmp_ln593_1_reg_2519 == 1'd0)) begin
            delay_bph_ce1 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_ce1;
        end else begin
            delay_bph_ce1 = 1'b0;
        end
    end else begin
        delay_bph_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln593_1_reg_2519 == 1'd1)) begin
            delay_bph_d0 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_d0;
        end else if ((icmp_ln593_1_reg_2519 == 1'd0)) begin
            delay_bph_d0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_d0;
        end else begin
            delay_bph_d0 = 'bx;
        end
    end else begin
        delay_bph_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln593_1_reg_2519 == 1'd1)) begin
            delay_bph_we0 = grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_delay_bph_we0;
        end else if ((icmp_ln593_1_reg_2519 == 1'd0)) begin
            delay_bph_we0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_bph_we0;
        end else begin
            delay_bph_we0 = 1'b0;
        end
    end else begin
        delay_bph_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        delay_bpl_address0 = 3'd0;
    end else if (((icmp_ln593_reg_2348 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_bpl_address0 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address0;
    end else if (((icmp_ln593_reg_2348 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_bpl_address0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        delay_bpl_address0 = grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_address0;
    end else begin
        delay_bpl_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln593_reg_2348 == 1'd1)) begin
            delay_bpl_address1 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_address1;
        end else if ((icmp_ln593_reg_2348 == 1'd0)) begin
            delay_bpl_address1 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_address1;
        end else begin
            delay_bpl_address1 = 'bx;
        end
    end else begin
        delay_bpl_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        delay_bpl_ce0 = 1'b1;
    end else if (((icmp_ln593_reg_2348 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_bpl_ce0 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce0;
    end else if (((icmp_ln593_reg_2348 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_bpl_ce0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        delay_bpl_ce0 = grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_bpl_ce0;
    end else begin
        delay_bpl_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln593_reg_2348 == 1'd1)) begin
            delay_bpl_ce1 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_ce1;
        end else if ((icmp_ln593_reg_2348 == 1'd0)) begin
            delay_bpl_ce1 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_ce1;
        end else begin
            delay_bpl_ce1 = 1'b0;
        end
    end else begin
        delay_bpl_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln593_reg_2348 == 1'd1)) begin
            delay_bpl_d0 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_d0;
        end else if ((icmp_ln593_reg_2348 == 1'd0)) begin
            delay_bpl_d0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_d0;
        end else begin
            delay_bpl_d0 = 'bx;
        end
    end else begin
        delay_bpl_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln593_reg_2348 == 1'd1)) begin
            delay_bpl_we0 = grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_delay_bpl_we0;
        end else if ((icmp_ln593_reg_2348 == 1'd0)) begin
            delay_bpl_we0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_bpl_we0;
        end else begin
            delay_bpl_we0 = 1'b0;
        end
    end else begin
        delay_bpl_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        delay_dhx_address0 = (3'd4 ^ working_key[104:102]);
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        delay_dhx_address0 = 3'd5;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        delay_dhx_address0 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        delay_dhx_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        delay_dhx_address0 = 3'd0;
    end else if (((icmp_ln593_1_reg_2519 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_dhx_address0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_dhx_address0 = grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_address0;
    end else begin
        delay_dhx_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        delay_dhx_address1 = (3'd3 ^ working_key[101:99]);
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        delay_dhx_address1 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        delay_dhx_address1 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        delay_dhx_address1 = 3'd4;
    end else begin
        delay_dhx_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | ((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18)))) begin
        delay_dhx_ce0 = 1'b1;
    end else if (((icmp_ln593_1_reg_2519 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        delay_dhx_ce0 = grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_delay_dhx_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_dhx_ce0 = grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_delay_dhx_ce0;
    end else begin
        delay_dhx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        delay_dhx_ce1 = 1'b1;
    end else begin
        delay_dhx_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        delay_dhx_d0 = delay_dhx_load_2_reg_2560;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        delay_dhx_d0 = reg_562;
    end else begin
        delay_dhx_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        delay_dhx_d1 = dlt_assign_3_reg_2480;
    end else if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30))) begin
        delay_dhx_d1 = reg_562;
    end else begin
        delay_dhx_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31))) begin
        delay_dhx_we0 = 1'b1;
    end else begin
        delay_dhx_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        delay_dhx_we1 = 1'b1;
    end else begin
        delay_dhx_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        delay_dltx_address0 = (3'd2 ^ working_key[98:96]);
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        delay_dltx_address0 = 3'd1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state19))) begin
        delay_dltx_address0 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        delay_dltx_address0 = 3'd0;
    end else if (((icmp_ln593_reg_2348 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_dltx_address0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        delay_dltx_address0 = grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_address0;
    end else begin
        delay_dltx_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_dltx_address1 = (3'd0 ^ working_key[95:93]);
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        delay_dltx_address1 = 3'd5;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state20))) begin
        delay_dltx_address1 = 3'd4;
    end else begin
        delay_dltx_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20) | ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        delay_dltx_ce0 = 1'b1;
    end else if (((icmp_ln593_reg_2348 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        delay_dltx_ce0 = grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_delay_dltx_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        delay_dltx_ce0 = grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_delay_dltx_ce0;
    end else begin
        delay_dltx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
        delay_dltx_ce1 = 1'b1;
    end else begin
        delay_dltx_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_dltx_d0 = delay_dltx_q0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        delay_dltx_d0 = reg_556;
    end else begin
        delay_dltx_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        delay_dltx_d1 = reg_556;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        delay_dltx_d1 = trunc_ln5_reg_2331;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        delay_dltx_d1 = delay_dltx_q1;
    end else begin
        delay_dltx_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
        delay_dltx_we0 = 1'b1;
    end else begin
        delay_dltx_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
        delay_dltx_we1 = 1'b1;
    end else begin
        delay_dltx_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | ((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
        grp_fu_2132_ce = 1'b1;
    end else begin
        grp_fu_2132_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        ilb_table_address0 = zext_ln582_1_fu_1774_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        ilb_table_address0 = zext_ln582_fu_1023_p1;
    end else begin
        ilb_table_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state15))) begin
        ilb_table_ce0 = 1'b1;
    end else begin
        ilb_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        qq4_code4_table_ce0 = 1'b1;
    end else begin
        qq4_code4_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        quant26bt_neg_ce0 = 1'b1;
    end else begin
        quant26bt_neg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        quant26bt_pos_ce0 = 1'b1;
    end else begin
        quant26bt_pos_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tqmf_address0 = (5'd23 ^ working_key[92:88]);
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tqmf_address0 = 5'd22;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state2))) begin
        tqmf_address0 = 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        tqmf_address0 = 5'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_address0 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tqmf_address0 = grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address0;
    end else begin
        tqmf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tqmf_address1 = (5'd1 ^ working_key[88:84]);
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_address1 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tqmf_address1 = grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_address1;
    end else begin
        tqmf_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tqmf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_ce0 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tqmf_ce0 = grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce0;
    end else begin
        tqmf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tqmf_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_ce1 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tqmf_ce1 = grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_tqmf_ce1;
    end else begin
        tqmf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tqmf_d0 = xin2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_d0 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_d0;
    end else begin
        tqmf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tqmf_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        tqmf_we0 = grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_tqmf_we0;
    end else begin
        tqmf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tqmf_we1 = 1'b1;
    end else begin
        tqmf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        wl_code_table_ce0 = 1'b1;
    end else begin
        wl_code_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln214_fu_747_p2 = (xb_fu_741_p2 + xa_4_fu_735_p2);

assign add_ln228_fu_826_p2 = (trunc_ln3_reg_2228 + trunc_ln2_fu_806_p4);

assign add_ln229_fu_831_p2 = (trunc_ln228_1_reg_2233 + trunc_ln4_fu_816_p4);

assign add_ln246_fu_1081_p2 = ($signed(sext_ln236_1_fu_1073_p1) + $signed(trunc_ln2_reg_2238));

assign add_ln263_fu_1184_p2 = ($signed(sext_ln239_reg_2337) + $signed(add_ln229_reg_2243));

assign add_ln278_fu_1512_p2 = (trunc_ln534_1_fu_1482_p4 + trunc_ln521_1_fu_1468_p4);

assign add_ln280_fu_1518_p2 = (trunc_ln278_1_fu_1502_p4 + trunc_ln10_fu_1492_p4);

assign add_ln306_fu_1814_p2 = (dlt_assign_3_reg_2480 + trunc_ln521_1_reg_2432);

assign add_ln321_fu_1915_p2 = (trunc_ln11_reg_2488 + add_ln280_reg_2437);

assign add_ln567_fu_959_p2 = ($signed(sext_ln567_1_fu_955_p1) + $signed(sext_ln567_fu_951_p1));

assign add_ln639_2_fu_1970_p2 = ($signed(sext_ln639_1_fu_1960_p1) + $signed(select_ln639_1_fu_1963_p3));

assign add_ln639_fu_1239_p2 = ($signed(sext_ln639_fu_1229_p1) + $signed(select_ln639_fu_1232_p3));

assign add_ln677_fu_1678_p2 = ($signed(sext_ln681_fu_1668_p1) + $signed(trunc_ln681_fu_1664_p1));

assign add_ln681_fu_1672_p2 = ($signed(sext_ln680_fu_1646_p1) + $signed(tmp_1_fu_1650_p6));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_done == 1'b0) | (grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state18_on_subcall_done = (((grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_done == 1'b0) & (icmp_ln593_reg_2348 == 1'd1)) | ((grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_done == 1'b0) & (icmp_ln593_reg_2348 == 1'd0)));
end

always @ (*) begin
    ap_block_state28_on_subcall_done = (((grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_done == 1'b0) & (icmp_ln593_1_reg_2519 == 1'd1)) | ((grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_done == 1'b0) & (icmp_ln593_1_reg_2519 == 1'd0)));
end

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_done == 1'b0) | (grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_done == 1'b0));
end

assign ap_return = or_ln_fu_2115_p3;

assign apl1_1_fu_1356_p3 = ((icmp_ln667_fu_1351_p2[0:0] == 1'b1) ? zext_ln655_fu_1345_p1 : apl1_reg_2383);

assign apl1_2_fu_1367_p2 = working_key[0] ? (16'd1 - zext_ln655_1_fu_1348_p1) :  (16'd0 - zext_ln655_1_fu_1348_p1);

assign apl1_3_fu_1383_p3 = ((icmp_ln669_fu_1377_p2[0:0] == 1'b1) ? apl1_2_fu_1367_p2 : trunc_ln655_fu_1363_p1);

assign apl1_4_fu_2021_p2 = ($signed(select_ln657_1_fu_2014_p3) + $signed(sext_ln657_1_fu_2010_p1));

assign apl1_5_fu_2074_p3 = ((icmp_ln667_1_fu_2069_p2[0:0] == 1'b1) ? zext_ln655_2_fu_2063_p1 : apl1_4_reg_2554);

assign apl1_6_fu_2085_p2 = working_key[1] ? (16'd19 - zext_ln655_3_fu_2066_p1) :  (16'd0 - zext_ln655_3_fu_2066_p1);

assign apl1_7_fu_2101_p3 = ((icmp_ln669_1_fu_2095_p2[0:0] == 1'b1) ? apl1_6_fu_2085_p2 : trunc_ln655_1_fu_2081_p1);

assign apl1_fu_1290_p2 = working_key[2]? ($signed(select_ln657_fu_1283_p3)) : ($signed(select_ln657_fu_1283_p3) + $signed(sext_ln657_fu_1279_p1));

assign apl2_1_fu_1296_p3 = ((icmp_ln642_reg_2378[0:0] == 1'b1) ? 16'd12288 : apl2_reg_2373);

assign apl2_2_fu_1312_p3 = ((icmp_ln644_fu_1306_p2[0:0] == 1'b1) ? 15'd20480 : trunc_ln626_fu_1302_p1);

assign apl2_3_fu_1976_p2 = ($signed(add_ln639_2_fu_1970_p2) + $signed(sext_ln631_3_fu_1956_p1));

assign apl2_4_fu_2027_p3 = ((icmp_ln642_1_reg_2549[0:0] == 1'b1) ? 16'd12288 : apl2_3_reg_2544);

assign apl2_5_fu_2043_p3 = ((icmp_ln644_1_fu_2037_p2[0:0] == 1'b1) ? 15'd20480 : trunc_ln626_1_fu_2033_p1);

assign apl2_fu_1245_p2 = ($signed(add_ln639_fu_1239_p2) + $signed(sext_ln631_2_fu_1225_p1));

assign decis_1_fu_1544_p1 = working_key[3] ? grp_fu_2125_p10 :grp_fu_2132_p2;

assign decis_1_fu_1544_p4 = working_key[4]? {{decis_1_fu_1544_p1[22:12]}}: {{decis_1_fu_1544_p1[24:12]}};

assign grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start = working_key[5] ? grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg : grp_encode_Pipeline_VITIS_LOOP_197_1_fu_475_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start = working_key[6] ? grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg :  grp_encode_Pipeline_VITIS_LOOP_208_2_fu_497_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start = working_key[7]? grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg : grp_encode_Pipeline_VITIS_LOOP_518_11_fu_527_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start = working_key[8]? grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg :grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start = working_key[9]? grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg :grp_encode_Pipeline_VITIS_LOOP_546_1_fu_503_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start = working_key[10]? grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg:grp_encode_Pipeline_VITIS_LOOP_595_12_fu_546_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start = working_key[11]? grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg :grp_encode_Pipeline_VITIS_LOOP_595_1_fu_521_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start = working_key[12]? grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg :grp_encode_Pipeline_VITIS_LOOP_602_23_fu_537_ap_start_reg;

assign grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start = working_key[13]? grp_encode_Pipeline_VITIS_LOOP_518_1_fu_487_ap_start_reg :grp_encode_Pipeline_VITIS_LOOP_602_2_fu_512_ap_start_reg;

assign grp_fu_2125_p1 = working_key[14] ? grp_fu_2132_p00 : grp_fu_2125_p10;

assign grp_fu_2125_p10 = detl;

assign grp_fu_2132_p0 =  working_key[15] ? grp_fu_2125_p10 :grp_fu_2132_p00;

assign grp_fu_2132_p00 = deth;

assign grp_fu_2132_p1 = 25'd564;

assign icmp_ln293_fu_1569_p2 = (($signed(m_3_fu_1562_p3) > $signed(zext_ln292_2_fu_1553_p1)) ? 1'b1 : 1'b0);

assign icmp_ln570_fu_985_p2 = ((select_ln568_fu_973_p3 > 17'd18432) ? 1'b1 : 1'b0);

assign icmp_ln593_1_fu_1818_p2 = ((dlt_assign_3_reg_2480 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln593_fu_1086_p2 = ((trunc_ln5_fu_1063_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln642_1_fu_1982_p2 = (($signed(apl2_3_fu_1976_p2) > $signed(16'd12288)) ? 1'b1 : 1'b0);

assign icmp_ln642_fu_1251_p2 = (($signed(apl2_fu_1245_p2) > $signed(16'd12288)) ? 1'b1 : 1'b0);

assign icmp_ln644_1_fu_2037_p2 = (($signed(apl2_4_fu_2027_p3) < $signed(16'd53248)) ? 1'b1 : 1'b0);

assign icmp_ln644_fu_1306_p2 = (($signed(apl2_1_fu_1296_p3) < $signed(16'd53248)) ? 1'b1 : 1'b0);

assign icmp_ln667_1_fu_2069_p2 = (($signed(apl1_4_reg_2554) > $signed(zext_ln655_2_fu_2063_p1)) ? 1'b1 : 1'b0);

assign icmp_ln667_fu_1351_p2 = (($signed(apl1_reg_2383) > $signed(zext_ln655_fu_1345_p1)) ? 1'b1 : 1'b0);

assign icmp_ln669_1_fu_2095_p2 = (($signed(apl1_5_fu_2074_p3) < $signed(sext_ln669_1_fu_2091_p1)) ? 1'b1 : 1'b0);

assign icmp_ln669_fu_1377_p2 = (($signed(apl1_1_fu_1356_p3) < $signed(sext_ln669_fu_1373_p1)) ? 1'b1 : 1'b0);

assign icmp_ln684_fu_1704_p2 = ((select_ln682_fu_1692_p3 > 31'd22528) ? 1'b1 : 1'b0);

assign lshr_ln_fu_892_p4 = {{ril_2_fu_885_p3[5:2]}};

assign m_2_fu_1557_p2 = (32'd0 - sub_ln280_reg_2442);

assign m_3_fu_1562_p3 = ((tmp_10_fu_1537_p3[0:0] == 1'b1) ? m_2_fu_1557_p2 : sub_ln280_reg_2442);

assign m_4_fu_860_p3 = ((tmp_2_fu_846_p3[0:0] == 1'b1) ? m_fu_854_p2 : sub_ln229_fu_836_p2);

assign m_fu_854_p2 = (32'd0 - sub_ln229_fu_836_p2);

assign mul_ln188_fu_573_p1 = 38'd274877906900;

assign mul_ln203_fu_627_p1 = 39'd549755813844;

assign mul_ln297_fu_1716_p1 = mul_ln297_fu_1716_p10;

assign mul_ln297_fu_1716_p10 = deth;

assign mul_ln628_1_fu_1845_p1 = sext_ln628_2_fu_1838_p1;

assign mul_ln628_fu_1114_p1 = sext_ln628_fu_1107_p1;

assign mul_ln631_1_fu_1879_p1 = sext_ln628_2_fu_1838_p1;

assign mul_ln631_fu_1148_p1 = sext_ln628_fu_1107_p1;

assign or_ln_fu_2115_p3 = {{select_ln297_reg_2460}, {ril_2_reg_2276}};

assign pl2_1_fu_1443_p3 = {{rh2}, {1'd0}};

assign pl2_fu_701_p3 = {{rlt2}, {1'd0}};

assign pl_1_fu_779_p2 = (mul_ln533_reg_2213 + mul_ln529_reg_2208);

assign pl_2_fu_1421_p3 = {{rh1}, {1'd0 ^ working_key[63]}};

assign pl_3_fu_1478_p2 = (mul_ln533_1_reg_2427 + mul_ln529_1_reg_2422);

assign pl_fu_679_p3 = {{rlt1}, {1'd0 ^ working_key[62]}};

assign qq4_code4_table_address0 = zext_ln236_fu_902_p1;

assign quant26bt_neg_address0 = zext_ln556_fu_879_p1;

assign quant26bt_pos_address0 = zext_ln556_fu_879_p1;

assign ril_2_fu_885_p3 = ((tmp_2_reg_2251[0:0] == 1'b1) ? quant26bt_neg_q0 : quant26bt_pos_q0);

assign select_ln284_fu_1575_p3 = ((tmp_11_reg_2449[0:0] == 1'b1) ? 2'd1 : 2'd3);

assign select_ln294_fu_1582_p3 = ((tmp_11_reg_2449[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln297_fu_1589_p3 = ((icmp_ln293_reg_2455[0:0] == 1'b1) ? select_ln294_fu_1582_p3 : select_ln284_fu_1575_p3);

assign select_ln546_fu_872_p3 = ((targetBlock_reg_2261[0:0] == 1'b1) ? 5'd30 : mil_loc_fu_310);

assign select_ln568_fu_973_p3 = ((tmp_5_fu_965_p3[0:0] == 1'b1) ? 17'd0 : add_ln567_fu_959_p2);

assign select_ln570_fu_991_p3 = ((icmp_ln570_reg_2306[0:0] == 1'b1) ? 15'd18432 : trunc_ln563_reg_2301);

assign select_ln628_1_fu_1950_p3 = ((tmp_13_reg_2523[0:0] == 1'b1) ? tmp_7_fu_1941_p4 : tmp_6_reg_2529);

assign select_ln628_fu_1219_p3 = ((tmp_8_reg_2352[0:0] == 1'b1) ? tmp_4_fu_1210_p4 : tmp_3_reg_2358);

assign select_ln639_1_fu_1963_p3 = ((tmp_14_reg_2534[0:0] == 1'b1) ? 16'd65408 : 16'd128);

assign select_ln639_fu_1232_p3 = ((tmp_9_reg_2363[0:0] == 1'b1) ? 16'd65408 : 16'd128);

assign select_ln657_1_fu_2014_p3 = ((tmp_13_reg_2523[0:0] == 1'b1) ? 17'd130880 : 17'd192);

assign select_ln657_fu_1283_p3 = ((tmp_8_reg_2352[0:0] == 1'b1) ? 17'd130880 : 17'd192);

assign select_ln682_fu_1692_p3 = ((tmp_12_fu_1684_p3[0:0] == 1'b1) ? 31'd0 : add_ln677_fu_1678_p2);

assign select_ln684_fu_1742_p3 = ((icmp_ln684_reg_2475[0:0] == 1'b1) ? 15'd22528 : trunc_ln677_reg_2470);

assign sext_ln194_1_fu_612_p1 = $signed(shl_ln194_1_fu_604_p3);

assign sext_ln194_fu_600_p1 = $signed(shl_ln_fu_592_p3);

assign sext_ln203_fu_732_p1 = $signed(sub_ln204_reg_2194);

assign sext_ln204_1_fu_729_p1 = $signed(mul_ln203_reg_2189);

assign sext_ln204_2_fu_641_p1 = $signed(shl_ln1_fu_633_p3);

assign sext_ln204_3_fu_653_p1 = $signed(shl_ln204_1_fu_645_p3);

assign sext_ln236_1_fu_1073_p1 = trunc_ln5_fu_1063_p4;

assign sext_ln239_fu_1077_p1 = trunc_ln5_fu_1063_p4;

assign sext_ln531_1_fu_1779_p0 = ah1;

assign sext_ln531_1_fu_1779_p1 = sext_ln531_1_fu_1779_p0;

assign sext_ln531_fu_1057_p0 = al1;

assign sext_ln531_fu_1057_p1 = sext_ln531_fu_1057_p0;

assign sext_ln533_2_fu_1782_p0 = ah2;

assign sext_ln533_2_fu_1782_p1 = sext_ln533_2_fu_1782_p0;

assign sext_ln533_fu_1060_p0 = al2;

assign sext_ln533_fu_1060_p1 = sext_ln533_fu_1060_p0;

assign sext_ln567_1_fu_955_p1 = $signed(wl_code_table_q0);

assign sext_ln567_fu_951_p1 = $signed(trunc_ln6_fu_941_p4);

assign sext_ln628_2_fu_1838_p1 = add_ln306_reg_2513;

assign sext_ln628_fu_1107_p1 = add_ln246_reg_2342;

assign sext_ln631_2_fu_1225_p1 = $signed(select_ln628_fu_1219_p3);

assign sext_ln631_3_fu_1956_p1 = $signed(select_ln628_1_fu_1950_p3);

assign sext_ln639_1_fu_1960_p1 = $signed(trunc_ln639_1_reg_2539);

assign sext_ln639_fu_1229_p1 = $signed(trunc_ln7_reg_2368);

assign sext_ln657_1_fu_2010_p1 = $signed(trunc_ln656_1_fu_2000_p4);

assign sext_ln657_fu_1279_p1 = $signed(trunc_ln9_fu_1269_p4);

assign sext_ln669_1_fu_2091_p1 = apl1_6_fu_2085_p2;

assign sext_ln669_fu_1373_p1 = apl1_2_fu_1367_p2;

assign sext_ln680_fu_1646_p1 = wd_1_fu_1636_p4;

assign sext_ln681_fu_1668_p1 = wd_1_fu_1636_p4;

assign shl_ln194_1_fu_604_p1 = reg_552;

assign shl_ln194_1_fu_604_p3 = {{shl_ln194_1_fu_604_p1}, {2'd0 ^ working_key[1:0]}};

assign shl_ln1_fu_633_p3 = {{tqmf_q0}, {4'd0 ^ working_key[5:2]}};

assign shl_ln204_1_fu_645_p3 = {{tqmf_q0}, {2'd0 ^ working_key[7:6] }};

assign shl_ln2_fu_923_p3 = {{nbl}, {7'd0 ^ working_key[14:8]}};

assign shl_ln3_fu_1043_p3 = {{wd3_fu_1037_p2}, {3'd0 ^ working_key[17:15]}};

assign shl_ln583_1_fu_1800_p3 = {{wd3_2_fu_1794_p2}, {3'd0^ working_key[20:18]}};

assign shl_ln639_1_fu_1893_p1 = ah2;

assign shl_ln639_1_fu_1893_p3 = {{shl_ln639_1_fu_1893_p1}, {7'd0 ^ working_key[27:21]}};

assign shl_ln656_1_fu_1988_p1 = ah1;

assign shl_ln656_1_fu_1988_p3 = {{shl_ln656_1_fu_1988_p1}, {8'd0^ working_key[35:28]}};

assign shl_ln6_fu_1162_p1 = al2;

assign shl_ln6_fu_1162_p3 = {{shl_ln6_fu_1162_p1}, {7'd0^ working_key[42:36]}};

assign shl_ln7_fu_1257_p1 = al1;

assign shl_ln7_fu_1257_p3 = {{shl_ln7_fu_1257_p1}, {8'd0^ working_key[50:43]}};

assign shl_ln8_fu_1618_p3 = {{nbh}, {7'd0^ working_key[57:51]}};

assign shl_ln_fu_592_p1 = reg_552;

assign shl_ln_fu_592_p3 = {{shl_ln_fu_592_p1}, {4'd0^ working_key[61:58]}};

assign sub_ln204_fu_657_p2 = ($signed(sext_ln204_2_fu_641_p1) - $signed(sext_ln204_3_fu_653_p1));

assign sub_ln215_fu_763_p2 = (xa_4_fu_735_p2 - xb_fu_741_p2);

assign sub_ln229_fu_836_p2 = (trunc_ln_reg_2218 - add_ln228_fu_826_p2);

assign sub_ln280_fu_1524_p2 = (trunc_ln1_reg_2223 - add_ln278_fu_1512_p2);

assign sub_ln566_fu_935_p2 = (zext_ln566_1_fu_931_p1 - zext_ln566_fu_919_p1);

assign sub_ln582_1_fu_1785_p2 = ($signed(4'd11) - $signed(trunc_ln579_1_reg_2493));

assign sub_ln582_1cast_fu_1790_p1 = sub_ln582_1_fu_1785_p2;

assign sub_ln582_fu_1028_p2 = ($signed(4'd9) - $signed(trunc_ln8_reg_2311));

assign sub_ln582cast_fu_1033_p1 = sub_ln582_fu_1028_p2;

assign sub_ln629_1_fu_1859_p2 = (18'd0 - wd2_1_fu_1831_p3);

assign sub_ln629_fu_1128_p2 = (18'd0 - wd2_fu_1100_p3);

assign sub_ln639_1_fu_1900_p2 = ($signed(shl_ln639_1_fu_1893_p3) - $signed(sext_ln533_2_reg_2508));

assign sub_ln639_fu_1169_p2 = ($signed(shl_ln6_fu_1162_p3) - $signed(sext_ln533_reg_2326));

assign sub_ln656_1_fu_1995_p2 = ($signed(shl_ln656_1_fu_1988_p3) - $signed(sext_ln531_1_reg_2503));

assign sub_ln656_fu_1264_p2 = ($signed(shl_ln7_fu_1257_p3) - $signed(sext_ln531_reg_2321));

assign sub_ln680_fu_1630_p2 = (zext_ln680_1_fu_1626_p1 - zext_ln680_fu_1614_p1);

assign tmp_10_fu_1537_p3 = sub_ln280_reg_2442[32'd31];

assign tmp_12_fu_1684_p3 = add_ln681_fu_1672_p2[32'd31];

assign tmp_2_fu_846_p3 = sub_ln229_fu_836_p2[32'd31];

assign tmp_4_fu_1210_p1 = al1;

assign tmp_4_fu_1210_p4 = {{tmp_4_fu_1210_p1[15:5]}};

assign tmp_5_fu_965_p3 = add_ln567_fu_959_p2[32'd16];

assign tmp_7_fu_1941_p1 = ah1;

assign tmp_7_fu_1941_p4 = {{tmp_7_fu_1941_p1[15:5]}};

assign trunc_ln10_fu_1492_p4 = {{zl_4_loc_fu_306[44:14]}};

assign trunc_ln278_1_fu_1502_p4 = {{pl_3_fu_1478_p2[45:15]}};

assign trunc_ln2_fu_806_p4 = {{zl_1_loc_fu_314[45:14]}};

assign trunc_ln4_fu_816_p4 = {{zl_1_loc_fu_314[44:14]}};

assign trunc_ln521_1_fu_1468_p4 = {{zl_4_loc_fu_306[45:14]}};

assign trunc_ln534_1_fu_1482_p4 = {{pl_3_fu_1478_p2[46:15]}};

assign trunc_ln563_fu_981_p1 = select_ln568_fu_973_p3[14:0];

assign trunc_ln5_fu_1063_p4 = {{grp_fu_2125_p2[30:15]}};

assign trunc_ln626_1_fu_2033_p1 = apl2_4_fu_2027_p3[14:0];

assign trunc_ln626_fu_1302_p1 = apl2_1_fu_1296_p3[14:0];

assign trunc_ln655_1_fu_2081_p1 = apl1_5_fu_2074_p3[15:0];

assign trunc_ln655_fu_1363_p1 = apl1_1_fu_1356_p3[15:0];

assign trunc_ln656_1_fu_2000_p4 = {{sub_ln656_1_fu_1995_p2[23:8]}};

assign trunc_ln677_fu_1700_p1 = select_ln682_fu_1692_p3[14:0];

assign trunc_ln681_fu_1664_p1 = tmp_1_fu_1650_p6[30:0];

assign trunc_ln6_fu_941_p4 = {{sub_ln566_fu_935_p2[22:7]}};

assign trunc_ln9_fu_1269_p4 = {{sub_ln656_fu_1264_p2[23:8]}};

assign wd1_1_fu_1754_p4 = {{select_ln684_fu_1742_p3[10:6]}};

assign wd1_fu_1003_p4 = {{select_ln570_fu_991_p3[10:6]}};

assign wd2_1_fu_1831_p1 = ah1;

assign wd2_1_fu_1831_p3 = {{wd2_1_fu_1831_p1}, {2'd0}};

assign wd2_fu_1100_p1 = al1;

assign wd2_fu_1100_p3 = {{wd2_fu_1100_p1}, {2'd0}};

assign wd3_1_fu_1326_p2 = (15'd15360 - apl2_2_fu_1312_p3);

assign wd3_2_fu_1794_p2 = ilb_table_q0 >> sub_ln582_1cast_fu_1790_p1;

assign wd3_3_fu_2057_p2 = (15'd15360 - apl2_5_fu_2043_p3);

assign wd3_fu_1037_p2 = ilb_table_q0 >> sub_ln582cast_fu_1033_p1;

assign wd_1_fu_1636_p4 = {{sub_ln680_fu_1630_p2[22:7]}};

assign wl_code_table_address0 = zext_ln236_fu_902_p1;

assign xa_4_fu_735_p2 = ($signed(sext_ln204_1_fu_729_p1) + $signed(xa_2_loc_fu_318));

assign xa_fu_616_p2 = ($signed(sext_ln194_fu_600_p1) - $signed(sext_ln194_1_fu_612_p1));

assign xb_fu_741_p2 = ($signed(sext_ln203_fu_732_p1) + $signed(xb_2_loc_fu_322));

assign zext_ln236_fu_902_p1 = lshr_ln_fu_892_p4;

assign zext_ln292_2_fu_1553_p1 = decis_1_fu_1544_p4;

assign zext_ln556_fu_879_p1 = select_ln546_fu_872_p3;

assign zext_ln566_1_fu_931_p1 = shl_ln2_fu_923_p3;

assign zext_ln566_fu_919_p1 = nbl;

assign zext_ln582_1_fu_1774_p1 = wd1_1_fu_1754_p4;

assign zext_ln582_fu_1023_p1 = wd1_fu_1003_p4;

assign zext_ln655_1_fu_1348_p1 = wd3_1_reg_2394;

assign zext_ln655_2_fu_2063_p1 = wd3_3_reg_2565;

assign zext_ln655_3_fu_2066_p1 = wd3_3_reg_2565;

assign zext_ln655_fu_1345_p1 = wd3_1_reg_2394;

assign zext_ln680_1_fu_1626_p1 = shl_ln8_fu_1618_p3;

assign zext_ln680_fu_1614_p1 = nbh;

always @ (posedge ap_clk) begin
    detl[2:0] <= 3'b000;
    deth[2:0] <= 3'b000;
    xa_reg_2184[1:0] <= 2'b00;
    sub_ln204_reg_2194[1:0] <= 2'b00;
end

assign working_key[149:0]= locking_key[149:0];

endmodule //encode
